# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sub_orgnizations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Organization'),
        ),
    ]
