# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20170608_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='courses_set', to='testapp.Teacher'),
        ),
    ]
