# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20170609_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='in_groups_set', through='testapp.Membership', to='testapp.Person'),
        ),
    ]
