# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_info',
        ),
    ]
