# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.Place')),
                ('customers', models.ManyToManyField(related_name='provider', to='testapp.Place')),
            ],
            bases=('testapp.place',),
        ),
    ]
